version: "3.8"

services:
  ca.example.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    volumes:
      - ./fabric/ca:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'

  orderer.example.com:
    image: hyperledger/fabric-orderer:2.5
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false  # Set true if using TLS
    ports:
      - "7050:7050"
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
      - ./genesis.block:/var/hyperledger/orderer/genesis.block

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./fabric/peer:/var/hyperledger/production
    ports:
      - "7051:7051"

  cli:
    image: hyperledger/fabric-tools:2.5
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com
    volumes:
      - ./fabric/chaincode:/opt/gopath/src/github.com/chaincode
      - ./shared:/app/shared
    working_dir: /opt/gopath/src/github.com/chaincode
    tty: true

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./shared/ipfs/data:/data/ipfs

  load:
    build:
      context: .
      dockerfile: load/Dockerfile
    depends_on:
      - peer0.org1.example.com
    volumes:
      - ./shared:/app/shared

  messaging:
    build: ./shared/messaging
    depends_on:
      - peer0.org1.example.com
    ports:
      - "8081:8081"
    volumes:
      - ./shared:/app/shared

  transfer:
    build:
      context: .
      dockerfile: transfer/Dockerfile
    depends_on:
      - messaging
      - ipfs
    volumes:
      - ./shared:/app/shared  # Mount the shared folder to the container


networks:
  default:
    name: datafly-net
